"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-20 10:49:56.867426
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='active', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['organizations.id'], name=op.f('fk_organizations_parent_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations'))
    )
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=False)
    op.create_index(op.f('ix_organizations_parent_id'), 'organizations', ['parent_id'], unique=False)
    op.create_index(op.f('ix_organizations_type'), 'organizations', ['type'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('openid', sa.String(length=64), nullable=True),
    sa.Column('unionid', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('wechat_id', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('bio', sa.String(length=500), nullable=True),
    sa.Column('role', sa.String(length=32), server_default='user', nullable=False),
    sa.Column('status', sa.String(length=32), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_index(op.f('ix_users_openid'), 'users', ['openid'], unique=True)
    op.create_index(op.f('ix_users_unionid'), 'users', ['unionid'], unique=False)
    op.create_table('activities',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('cover_url', sa.String(length=512), nullable=True),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('organizer', sa.String(length=200), nullable=True),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('signup_start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('signup_end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='draft', nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_activities_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activities'))
    )
    op.create_index(op.f('ix_activities_title'), 'activities', ['title'], unique=False)
    op.create_table('articles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('cover_url', sa.String(length=512), nullable=True),
    sa.Column('summary', sa.String(length=500), nullable=True),
    sa.Column('content', sa.Text(), server_default='', nullable=False),
    sa.Column('is_pinned', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('status', sa.String(length=32), server_default='draft', nullable=False),
    sa.Column('publish_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_articles_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_articles'))
    )
    op.create_index(op.f('ix_articles_title'), 'articles', ['title'], unique=False)
    op.create_table('directory_permissions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('organization_id', sa.BigInteger(), nullable=False),
    sa.Column('scope_type', sa.String(length=32), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_directory_permissions_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_directory_permissions'))
    )
    op.create_index(op.f('ix_directory_permissions_organization_id'), 'directory_permissions', ['organization_id'], unique=True)
    op.create_table('memberships',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('organization_id', sa.BigInteger(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_memberships_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_memberships_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memberships')),
    sa.UniqueConstraint('user_id', 'organization_id', name='user_organization')
    )
    op.create_index(op.f('ix_memberships_organization_id'), 'memberships', ['organization_id'], unique=False)
    op.create_index(op.f('ix_memberships_user_id'), 'memberships', ['user_id'], unique=False)
    op.create_table('relays',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='open', nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_relays_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_relays'))
    )
    op.create_index(op.f('ix_relays_title'), 'relays', ['title'], unique=False)
    op.create_table('activity_signups',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('activity_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('remark', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='signed', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], name=op.f('fk_activity_signups_activity_id_activities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_activity_signups_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_signups')),
    sa.UniqueConstraint('activity_id', 'user_id', name='signup_activity_user')
    )
    op.create_index(op.f('ix_activity_signups_activity_id'), 'activity_signups', ['activity_id'], unique=False)
    op.create_index(op.f('ix_activity_signups_user_id'), 'activity_signups', ['user_id'], unique=False)
    op.create_table('article_scopes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('article_id', sa.BigInteger(), nullable=False),
    sa.Column('organization_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_article_scopes_article_id_articles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_article_scopes_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_article_scopes'))
    )
    op.create_index(op.f('ix_article_scopes_article_id'), 'article_scopes', ['article_id'], unique=False)
    op.create_index(op.f('ix_article_scopes_organization_id'), 'article_scopes', ['organization_id'], unique=False)
    op.create_table('photos',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('activity_id', sa.BigInteger(), nullable=False),
    sa.Column('uploader_id', sa.BigInteger(), nullable=True),
    sa.Column('file_url', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], name=op.f('fk_photos_activity_id_activities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], name=op.f('fk_photos_uploader_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_photos'))
    )
    op.create_index(op.f('ix_photos_activity_id'), 'photos', ['activity_id'], unique=False)
    op.create_table('relay_fields',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('relay_id', sa.BigInteger(), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('field_type', sa.String(length=32), nullable=False),
    sa.Column('required', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('options_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['relay_id'], ['relays.id'], name=op.f('fk_relay_fields_relay_id_relays'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_relay_fields'))
    )
    op.create_index(op.f('ix_relay_fields_relay_id'), 'relay_fields', ['relay_id'], unique=False)
    op.create_table('relay_responses',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('relay_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('response_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['relay_id'], ['relays.id'], name=op.f('fk_relay_responses_relay_id_relays'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_relay_responses_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_relay_responses')),
    sa.UniqueConstraint('relay_id', 'user_id', name='relay_response_user')
    )
    op.create_index(op.f('ix_relay_responses_relay_id'), 'relay_responses', ['relay_id'], unique=False)
    op.create_index(op.f('ix_relay_responses_user_id'), 'relay_responses', ['user_id'], unique=False)
    op.create_table('activity_checkins',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('activity_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('signup_id', sa.BigInteger(), nullable=True),
    sa.Column('checkin_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('checkin_method', sa.String(length=32), server_default='qrcode', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], name=op.f('fk_activity_checkins_activity_id_activities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['signup_id'], ['activity_signups.id'], name=op.f('fk_activity_checkins_signup_id_activity_signups'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_activity_checkins_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_checkins')),
    sa.UniqueConstraint('activity_id', 'user_id', name='checkin_activity_user')
    )
    op.create_index(op.f('ix_activity_checkins_activity_id'), 'activity_checkins', ['activity_id'], unique=False)
    op.create_index(op.f('ix_activity_checkins_user_id'), 'activity_checkins', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activity_checkins_user_id'), table_name='activity_checkins')
    op.drop_index(op.f('ix_activity_checkins_activity_id'), table_name='activity_checkins')
    op.drop_table('activity_checkins')
    op.drop_index(op.f('ix_relay_responses_user_id'), table_name='relay_responses')
    op.drop_index(op.f('ix_relay_responses_relay_id'), table_name='relay_responses')
    op.drop_table('relay_responses')
    op.drop_index(op.f('ix_relay_fields_relay_id'), table_name='relay_fields')
    op.drop_table('relay_fields')
    op.drop_index(op.f('ix_photos_activity_id'), table_name='photos')
    op.drop_table('photos')
    op.drop_index(op.f('ix_article_scopes_organization_id'), table_name='article_scopes')
    op.drop_index(op.f('ix_article_scopes_article_id'), table_name='article_scopes')
    op.drop_table('article_scopes')
    op.drop_index(op.f('ix_activity_signups_user_id'), table_name='activity_signups')
    op.drop_index(op.f('ix_activity_signups_activity_id'), table_name='activity_signups')
    op.drop_table('activity_signups')
    op.drop_index(op.f('ix_relays_title'), table_name='relays')
    op.drop_table('relays')
    op.drop_index(op.f('ix_memberships_user_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_organization_id'), table_name='memberships')
    op.drop_table('memberships')
    op.drop_index(op.f('ix_directory_permissions_organization_id'), table_name='directory_permissions')
    op.drop_table('directory_permissions')
    op.drop_index(op.f('ix_articles_title'), table_name='articles')
    op.drop_table('articles')
    op.drop_index(op.f('ix_activities_title'), table_name='activities')
    op.drop_table('activities')
    op.drop_index(op.f('ix_users_unionid'), table_name='users')
    op.drop_index(op.f('ix_users_openid'), table_name='users')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_organizations_type'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_parent_id'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
