"""extend user profile for chamber and business card

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-20 12:27:50.328159
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name_en', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('profession', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('profession_en', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('company_name', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('company_address', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('company_founded_at', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('position', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('business_description', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('referrals_needed', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('personal_experience', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('resources_offered', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('chamber_chapter', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('chamber_member_no', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('chamber_join_date', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('chamber_score', sa.Integer(), nullable=True))
    op.alter_column('users', 'bio',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'bio',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.drop_column('users', 'chamber_score')
    op.drop_column('users', 'chamber_join_date')
    op.drop_column('users', 'chamber_member_no')
    op.drop_column('users', 'chamber_chapter')
    op.drop_column('users', 'resources_offered')
    op.drop_column('users', 'personal_experience')
    op.drop_column('users', 'referrals_needed')
    op.drop_column('users', 'business_description')
    op.drop_column('users', 'position')
    op.drop_column('users', 'company_founded_at')
    op.drop_column('users', 'company_address')
    op.drop_column('users', 'company_name')
    op.drop_column('users', 'profession_en')
    op.drop_column('users', 'profession')
    op.drop_column('users', 'name_en')
    # ### end Alembic commands ###
